const AXES=[["softness","Softness"],["bounce","Bounce"],["stability","Stability"],["guidance","Guidance"],["responsiveness","Responsiveness"],["agility","Agility"],["comfort","Comfort"]];
const DIRECTIONS=[["all","ทั้งหมด"],["softness","นุ่มขึ้น"],["bounce","เด้งขึ้น"],["stability","มั่นคงขึ้น"],["responsiveness","ตอบสนองขึ้น"],["agility","คล่องขึ้น"],["comfort","สบายขึ้น"]];
let DB,currentId,direction="all";const $=id=>document.getElementById(id);
function labelForMatch(x){return x>=90?"VERY CLOSE":x>=80?"CLOSE":x>=70?"RELATED":x>=60?"DISTANT":"VERY DISTANT"}
function shoe(id){return DB.shoes.find(x=>x.id===id)}
function meter(v){return `<div class="meter">${[1,2,3,4,5].map(i=>`<span class="seg ${i<=v?"on":""}"></span>`).join("")}</div>`}
function mini(v){return `<div class="mini-meter"><div class="mini-fill" style="width:${v*20}%"></div></div>`}
function renderDirections(){$("directionChips").innerHTML=DIRECTIONS.map(([id,th])=>`<button class="chip ${direction===id?"active":""}" data-dir="${id}">${th}</button>`).join("");document.querySelectorAll("[data-dir]").forEach(b=>b.onclick=()=>{direction=b.dataset.dir;renderDirections();renderRelations()})}
function render(){const s=shoe(currentId);$("hero").innerHTML=`<div class="shoe-art"><div class="shoe-shape"></div></div><div><div class="eyebrow">ASICS · ${s.category.toUpperCase()}</div><h2>${s.id}</h2><div class="meta"><span class="pill">${s.ride}</span><span class="pill">${s.category}</span></div><p class="human">${s.human}</p></div>`;$("axisGrid").innerHTML=AXES.map(([k,n])=>`<div class="axis-card"><div class="axis-top"><span class="axis-label">${n}</span><span class="axis-value">${s[k]}/5</span></div>${meter(s[k])}</div>`).join("");renderRelations();$("comparePanel").classList.add("hidden")}
function filteredRelations(){const src=shoe(currentId);return DB.relations.filter(r=>r.source===currentId).filter(r=>direction==="all"?true:shoe(r.target)[direction]>src[direction])}
function renderRelations(){const rs=filteredRelations();$("relationCount").textContent=`${rs.length} direct relation${rs.length===1?"":"s"}`;$("relationList").innerHTML=rs.length?rs.map(r=>`<article class="relation" data-rel="${r.id}"><div class="rel-top"><div><div class="eyebrow">${r.type}</div><h3>→ ${r.target}</h3></div><div class="match">${r.match.toFixed(1)}%</div></div><div class="rel-delta">${r.delta}</div><div class="rel-meta"><span class="tiny">${labelForMatch(r.match)}</span><span class="tiny">Strength ${r.strength}</span></div></article>`).join(""):`<div class="card" style="padding:20px;color:var(--muted)">ยังไม่มี direct relation ในทิศทางนี้ — ระบบจะไม่เดาคู่ให้เอง</div>`;document.querySelectorAll("[data-rel]").forEach(el=>el.onclick=()=>compare(DB.relations.find(r=>r.id===el.dataset.rel)))}
function compare(r){const a=shoe(r.source),b=shoe(r.target);$("comparePanel").classList.remove("hidden");$("compareTitle").textContent=`${a.id} → ${b.id}`;$("matchHero").innerHTML=`<div><div class="match-big">${r.match.toFixed(1)}%</div><div class="match-label">${labelForMatch(r.match)} · Character Match</div></div><div class="badge">Strength ${r.strength}</div>`;$("compareAxes").innerHTML=AXES.map(([k,n])=>{const d=b[k]-a[k],c=d>0?"up":d<0?"down":"same",arrow=d>0?"↑":d<0?"↓":"=";return `<div class="comp-row"><div class="comp-name">${n}</div>${mini(a[k])}<div>${a[k]}</div>${mini(b[k])}<div class="arrow ${c}">${arrow}</div></div>`}).join("");$("deltaSummary").innerHTML=`<strong>Character Change</strong><br>${r.delta}`;$("comparePanel").scrollIntoView({behavior:"smooth",block:"start"})}
async function init(){DB=await fetch("data/asics.json").then(r=>r.json());const sel=$("shoeSelect");sel.innerHTML=DB.shoes.map(s=>`<option value="${s.id}">${s.id} · ${s.category}</option>`).join("");currentId="GT-2000 15";sel.value=currentId;sel.onchange=()=>{currentId=sel.value;direction="all";renderDirections();render()};$("closeCompare").onclick=()=>$("comparePanel").classList.add("hidden");renderDirections();render()}
init();